version: '3.1'
services:
  flask-server:
    build:
      context: .
      dockerfile: ./script/Dockerfile

    container_name: "flask-server"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    # command: "flask --app www/server --debug run"
    networks:
      - flask-test-network

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - flask-test-network
    ports:
      - 5432:5432

  # adminer:
  #   image: adminer
  #   depends_on:
  #     - postgres_db
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - flask-test-network


networks:
  flask-test-network:
    driver: bridge

volumes:
  postgres: {}
