version: '3.1'
services:
  flask-server:
    build:
      context: .
      dockerfile: ./script/Dockerfile_test

    container_name: "flask-server-unittest"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    networks:
      - flask-test-network-test

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      -   postgres_unittest:/var/lib/postgresql/data
    networks:
      - flask-test-network-test
    ports:
      - 5433:5432

networks:
  flask-test-network-test:
    driver: bridge

volumes:
  postgres_unittest: {}
