version: 1
disable_existing_loggers: true
formatters:
  simpleFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'
  customFormat:
    '()': src.infa.logging.Logging.CustomFormat
handlers:
  fileHandler:
    formatter: simpleFormatter
    class: logging.FileHandler
    level: DEBUG
    filename: example.log
  consoleHandler:
    formatter: customFormat
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout

loggers:
  file:
    handlers: [fileHandler]
  console:
    handlers: [consoleHandler, fileHandler]
  sqlalchemy.engine:
    handlers: [fileHandler]
    qualname: sqlalchemy.engine
    propagate: false
  sqlalchemy.pool:
    handlers: [fileHandler]
    qualname: sqlalchemy.pool
    propagate: false
