[default]
DATABASE_URI = "default"
DATABASE_HOST = "127.0.0.1"
DATABASE_USER = "root"
DATABASE_PASSWORD = "root"

[development]
SQLALCHEMY_DATABASE_URI="postgresql://root:root@postgres_db/todo"
SQLALCHEMY_TRACK_MODIFICATIONS = 1
DATABASE_TYPE = "postgresql"
DATABASE_URI = "dev"
DATABASE_HOST = "postgres_db"
DATABASE_USER = "root"
DATABASE_PASSWORD = "root"
DATABASE_NAME= "todo"
LOGGER = "queueLogger"
LOGGING_FILE = "logging.yaml"
TYPE_LOGGING_FILE = "yaml"
SQLALCHEMY_ECHO = 1

[production]
DATABASE_URI = "production"
DATABASE_HOST = "127.0.0.1"
DATABASE_USER = "root"
DATABASE_PASSWORD = "root"